name: theme_extensions_builder_annotation
description: Annotations for the theme_extensions_builder
version: 1.0.0
repository: https://github.com/pro100andrey/theme_extensions_builder
issue_tracker: https://github.com/pro100andrey/theme_extensions_builder/issues
homepage: https://github.com/pro100andrey/theme_extensions_builder
documentation: https://github.com/pro100andrey/theme_extensions_builder/blob/main/packages/theme_extensions_builder/README.md

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  meta: ^1.8.0

dev_dependencies:
  flutter_lints: ^2.0.0